export const demoData = {
  __version: "demo-safe-v1",
  generatedAt: "2026-06-05",
  leads: [
    {
      id: "demo-lead-001",
      sourceId: "DEMO-001",
      name: "Demo Tuition Centre",
      list: "Demo Education Leads",
      niche: "Tuition centre",
      location: "Bengaluru",
      address: "Hidden in demo mode",
      phone: "Hidden until database is connected",
      alternatePhone: "",
      email: "Hidden until database is connected",
      websiteStatus: "No visible official website found",
      rating: "4.7",
      reviews: "80+",
      sourceLink: "",
      otherLink: "",
      leadReason: "Safe demo record showing how no-website education leads will appear after database connection.",
      pitch: "Build a simple website and enquiry CRM to help parents find class details and contact the centre quickly.",
      decisionMaker: "Not shown in demo",
      openingHours: "Not shown in demo",
      notes: "This is placeholder data only. Real leads load from Supabase.",
      status: "WhatsApp Sent",
      owner: "Sales Team",
      lastAction: "WhatsApp outreach sent",
      whatsappSent: true,
      whatsappReplied: false,
      emailSent: false,
      nextFollowUp: "",
      proposalStatus: "None",
      clientValue: "",
      createdAt: "2026-06-05",
      updatedAt: "2026-06-05",
    },
    {
      id: "demo-lead-002",
      sourceId: "DEMO-002",
      name: "Demo Coaching Academy",
      list: "Demo Education Leads",
      niche: "Coaching academy",
      location: "Pune",
      address: "Hidden in demo mode",
      phone: "Hidden until database is connected",
      alternatePhone: "",
      email: "Hidden until database is connected",
      websiteStatus: "Weak existing website",
      rating: "4.5",
      reviews: "45+",
      sourceLink: "",
      otherLink: "",
      leadReason: "Safe demo record for weak-website outreach and follow-up tracking.",
      pitch: "Improve trust, admissions enquiries, WhatsApp follow-ups, and demo class booking.",
      decisionMaker: "Not shown in demo",
      openingHours: "Not shown in demo",
      notes: "This is placeholder data only. Real leads load from Supabase.",
      status: "Replied",
      owner: "Sales Team",
      lastAction: "WhatsApp reply received",
      whatsappSent: true,
      whatsappReplied: true,
      emailSent: false,
      nextFollowUp: "",
      proposalStatus: "None",
      clientValue: "",
      createdAt: "2026-06-05",
      updatedAt: "2026-06-05",
    },
    {
      id: "demo-lead-003",
      sourceId: "DEMO-003",
      name: "Demo Training Institute",
      list: "Demo Education Leads",
      niche: "Training institute",
      location: "Bengaluru",
      address: "Hidden in demo mode",
      phone: "Hidden until database is connected",
      alternatePhone: "",
      email: "Hidden until database is connected",
      websiteStatus: "No visible official website found",
      rating: "4.8",
      reviews: "120+",
      sourceLink: "",
      otherLink: "",
      leadReason: "Safe demo record for proposal-stage tracking.",
      pitch: "Website plus small CRM for enquiry capture, follow-up reminders, and admissions visibility.",
      decisionMaker: "Not shown in demo",
      openingHours: "Not shown in demo",
      notes: "This is placeholder data only. Real proposals load from Supabase.",
      status: "Proposal Sent",
      owner: "Sales Team",
      lastAction: "Proposal sent",
      whatsappSent: true,
      whatsappReplied: true,
      emailSent: false,
      nextFollowUp: "",
      proposalStatus: "Sent",
      clientValue: "26000",
      createdAt: "2026-06-05",
      updatedAt: "2026-06-05",
    },
  ],
  proposals: [
    {
      id: "demo-proposal-001",
      leadName: "Demo Training Institute",
      client: "Demo Training Institute",
      status: "Sent",
      value: "26000",
      phone: "Hidden until database is connected",
      email: "Hidden until database is connected",
      owner: "Sales Team",
      service: "Website + small CRM",
      sentDate: "2026-06-05",
      validUntil: "2026-07-05",
      nextStep: "Design review pending",
      fileName: "Demo proposal.pdf",
      fileType: "application/pdf",
      filePath: "",
      notes: "Demo proposal record only. Real PDFs are stored in private Supabase Storage.",
    },
  ],
};
